### ISSUE TITLE
Classifier for Neuron Counterfactuals

### ISSUE THREAD

**Issue by hayakae** [M4xim4l/DiG-IN#2]
Thanks for the great work!
For Neuron Counterfactuals, I would like to know which classifier was used to generate the results in the paper (Fig.32, 33). Actually, I used resnet50 and the activation loss did not make any difference in the generated results.
Thank you in advance.

**Comment by M4xim4l** [comment]
Hi, thanks a lot for your interest in our work.
So for Figures 32 and 33, we used the Madry L2 adversarially robust model also used in [Salient ImageNet](https://salient-imagenet.cs.umd.edu/). This allows us to visualize the Neurons that they labeled on their website.

You can load the model by using classifier='madry_l2', though you need a model file for that. I uploaded it [here](https://drive.google.com/drive/folders/1me8msZ427i_f9qBbO0dFDpewM4LL4jlb?usp=drive_link). You simply have to download the .pt file and put it into a directory called "madry_l2" in the root directory and you should be able to load it.

The results from Figure 31 are created with a non-robust model (that is the Se-ResNet you can load with timm by using: "seresnet152d.ra2_in1k") and I think you should be able to also create neuron counterfactuals for that, though obviously the neuron numbers used in Figures 32/33 will not produce the same results for this model. 

In particular, the DEFAULT_NEURONS specified in "imagenet_neuron_counterfactuals.py" are for the robust ResNet50, so if you load a different model you will get very different results. 

Let me know if you need any more help with this!

**Comment by hayakae** [comment]
Many thanks for the detailed explanation and for providing the madry_l2 file!

In addition, if possible, could you provide the config.yaml file from which you generated Figures 32 and 33? I would like to know the detailed settings for the generation of Neuron Counterfactuals.

Thanks.

**Comment by M4xim4l** [comment]
Hi, sure. I think these parameters should still apply as is to the current codebase. 

```
model_path: CompVis/stable-diffusion-v1-4
use_double: false
resolution: 512
guidance_scale: 3.0
num_ddim_steps: 20
optim_params:
  sgd_steps: 20
  sgd_stepsize: 0.01
  sgd_optim: adam
  sgd_scheduler: null
  latent_lr_factor: 0.1
  conditioning_lr_factor: 1.0
  uncond_lr_factor: 1.0
  early_stopping_loss: null
  loss_steps: 3
  loss_steps_schedule: linear
  solver_order: 1
  optimize_latents: true
  optimize_conditioning: true
  per_timestep_conditioning_delta: true
  optimize_uncond: true
  per_timestep_uncond_delta: true
  normalize_gradients: false
  gradient_clipping: null
augmentation_num_cutouts: 16
augmentation_noise_sd: 0.005
augmentation_noise_schedule: const
wandb_project: null
gpu: 1
seed: 42
num_images_per_neuron: 50
classifier: madry_l2
target_class_neurons:
- - 83
  - 565
- - 120
  - 870
- - 537
  - 0
- - 146
  - 1697
- - 2
  - 1697
- - 576
  - 1772
- - 14
  - 660
- - 50
  - 341
- - 309
  - 595
- - 309
  - 1797
- - 537
  - 579
- - 537
  - 1855
- - 695
  - 1567
- - 695
  - 1635
results_folder: output_cvpr/imagenet_neuron_counterfactuals
results_sub_folder: neuron_blend
inversion_folder: output_cvpr/imagenet_inversions
imagenet_folder: /mnt/datasets/imagenet
loss: neuron_activation
regularizers:
- latent_foreground_l2
- px_foreground_l2
regularizers_ws:
- 25.0
- 250.0
segmentation_args:
  xa_map_resolution: 16
  xa_start_t: 0.5
  xa_end_t: 1.0
  xa_segmentation_squash: sqrt_0.3
  sam_segmentation: true
  sam_prompt: point
  sam_num_points: 10
  sam_foreground_threshold: 0.5
  sam_bb_quantile: 0.97
  postprocessing:
  - erosion_3
  - dilation_20
  - blur_45_30
p2p_params: null
mask_blend_params:
  do_mask_blend: true
  foreground_blend: true
  optimize_mask_blend: false
  initial_mask_blend_schedule:
  - threshold_0.3
  mask_blend_stepsize: 0.05

```
